# Generated by Django 6.1.1 on 2026-09-28 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('code', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=80)),
                ('hierarchy_rank', models.IntegerField(blank=True, null=True)),
                ('scope_level', models.CharField(blank=True, max_length=20, null=True)),
                ('is_opposition', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'muni_position',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='VoterPolitical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_slug', models.CharField(max_length=32)),
                ('voter_id', models.IntegerField()),
                ('municipality', models.CharField(blank=True, max_length=120, null=True)),
                ('upline_province_slug', models.CharField(blank=True, max_length=32, null=True)),
                ('upline_voter_id', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=191, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.CharField(blank=True, max_length=96, null=True)),
                ('role', models.ForeignKey(db_column='role_code', on_delete=django.db.models.deletion.PROTECT, to='municipal.position')),
            ],
            options={
                'db_table': 'muni_voter_political',
                'constraints': [models.UniqueConstraint(fields=('province_slug', 'voter_id'), name='uniq_province_voter')],
            },
        ),
    ]
