# Generated by Django 6.1.1 on 2026-09-28 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='voterpolitical',
            name='uniq_province_voter',
        ),
        migrations.RemoveField(
            model_name='voterpolitical',
            name='role',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='VoterPolitical',
        ),
    ]
